# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='disable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='enable_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
