# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[(b'admin', b'admin'), (b'teacher', b'teacher'), (b'customer', b'customer'), (b'user', b'user')], default='user', max_length=50),
        ),
    ]
