# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_lecture_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_date',
            field=models.DateTimeField(null=True),
        ),
    ]
