# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171209_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='course_date',
            new_name='lecture_date',
        ),
    ]
